### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by oxycast123** [nipund/iptvcast#1]
app crashing on (MainActivity.java:105)

**Comment by nipund** [comment]
Do you have a stack trace or any logcat output?

**Comment by oxycast123** [comment]
Note: C:\Users\oxytouch\Downloads\iptvcast\app\src\main\java\me\dayanath\iptvcast\MainActivity.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
this issues caused by deprecated api

**Comment by oxycast123** [comment]
More:
`03-16 09:08:48.173 28921-28921/? I/zygote64: Late-enabling -Xcheck:jni
03-16 09:08:48.230 28921-28928/? I/zygote64: Debugger is no longer active
03-16 09:08:48.357 28921-28921/? D/AndroidRuntime: Shutting down VM
03-16 09:08:48.362 28921-28921/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: me.dayanath.iptvcast, PID: 28921
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{me.dayanath.iptvcast/me.dayanath.iptvcast.MainActivity}: java.lang.IllegalStateException: Failed to initialize CastContext.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2906)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:172)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6637)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: java.lang.IllegalStateException: Failed to initialize CastContext.
                                                       at com.google.android.gms.cast.framework.CastContext.zzbu(Unknown Source:53)
                                                       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:14)
                                                       at me.dayanath.iptvcast.MainActivity.onCreate(MainActivity.java:105)
                                                       at android.app.Activity.performCreate(Activity.java:6975)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2784)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2906) 
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:172) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6637) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                    Caused by: java.lang.IllegalAccessException: java.lang.Class<me.dayanath.iptvcast.CastOptionsProvider> is not accessible from java.lang.Class<com.google.android.gms.cast.framework.CastContext>
                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                       at com.google.android.gms.cast.framework.CastContext.zzbu(Unknown Source:71)
                                                       at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:14) 
                                                       at me.dayanath.iptvcast.MainActivity.onCreate(MainActivity.java:105) 
                                                       at android.app.Activity.performCreate(Activity.java:6975) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2784) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2906) 
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:172) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6637) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
`

**Comment by nipund** [comment]
Try the current version.
